FROM github/super-linter:latest

ENV RUN_LOCAL=true
ENV VALIDATE_ALL_CODEBASE=false
ENV VALIDATE_YAML=true
ENV VALIDATE_JSON=true
ENV VALIDATE_XML=false
ENV VALIDATE_MD=true
ENV VALIDATE_BASH=true
ENV VALIDATE_PERL=false
ENV VALIDATE_PYTHON=false
ENV VALIDATE_RUBY=false
ENV VALIDATE_COFFEE=false
ENV VALIDATE_ANSIBLE=false
ENV VALIDATE_JAVASCRIPT_ES=false
ENV VALIDATE_JAVASCRIPT_STANDARD=false
ENV VALIDATE_TYPESCRIPT_ES=false
ENV VALIDATE_TYPESCRIPT_STANDARD=false
ENV VALIDATE_DOCKER=false
ENV VALIDATE_GO=false
ENV VALIDATE_TERRAFORM=false
ENV ANSIBLE_DIRECTORY=/ansible
ENV ACTIONS_RUNNER_DEBUG=false

COPY . /tmp/lint/

ENTRYPOINT ["/action/lib/linter.sh"]